version: '3.8'

services:
  front:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_BASE_URL=http://localhost:5173
    ports:
      - "5173:5173"
    depends_on:
      - web
    command: "npm run dev"


  web:
    build: 
      context: ./backend
      dockerfile: backend.dockerfile
    volumes:
      - ./backend:/app
    environment:
      - MIX_ENV=dev
      - POSTGRES_USER= ${POSTGRES_USER}
      - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}
      - POSTGRES_DB= ${POSTGRES_DB}
      - DATABASE_URL=ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: sh -c "mix deps.get && mix ecto.setup && mix phx.server"


  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER= ${POSTGRES_USER}
      - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}
      - POSTGRES_DB= ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
