version: '3.8'

services:
  front:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_BASE_URL=http://localhost:5173
    ports:
      - "5173:5173"
    depends_on:
      - web
    command: bash -c "npm run dev"


  web:
    build: 
      context: ./backend
      dockerfile: backend.dockerfile
    volumes:
      - ./backend:/app
    environment:
      - MIX_ENV=dev
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: bash -c "mix deps.get && mix ecto.setup && mix phx.server"


  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=$${{ secrets.POSTGRES_USER }}
      - POSTGRES_PASSWORD=$${{ secrets.POSTGRES_PASSWORD }}
      - POSTGRES_DB=timemanager_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
